[15.0][FIX] contract: Change web_ribbon text to title to make it translatable
OCA/contract pull request #1041
Opened 2024-01-29 09:12 UTC by victoralmau

Change web_ribbon text to title to make it translatable.

@Tecnativa.

2024-01-29 10:39 UTC, chienandalu approved these changes

2024-01-29 10:55 UTC, carlosdauden approved these changes

2024-01-29 11:19 UTC, pedrobaeza requested changes
Please do it all in one commit, as it doesn't deserve 2 commits, and don't modify the PO with POEdit (or adjust your POEdit to match the same line stripping), as the diff is heavy due to this.

2024-01-30 07:30 UTC, pedrobaeza approved these changes
/ocabot merge minor

2024-01-30 07:42 UTC, merged