[16.0][IMP] contract and contract_sale_generation: Add translations
OCA/contract pull request #1054
Opened 2024-03-11 13:48 UTC by aliciagaarzo

The _selection_generation_type() function has been modified to make the selection generation_type values translatable.

2024-03-12 08:53 UTC, amarcosg requested changes
With the requested changes you may need to reexport the translations

2024-03-12 08:53 UTC, amarcosg commented on contract/models/abstract_contract.py
> -        return [("invoice", "Invoice")]
Deleting the function you may break other funcionality that depends on it. Dont delete de function, just add the _ in the option

```
    @api.model
    def _selection_generation_type(self):
        return [("invoice", _("Invoice"))]
```

2024-03-12 08:53 UTC, amarcosg commented on contract_sale_generation/models/abstract_contract.py
> -    def _selection_generation_type(self):
Same dont delete the function just add the _ `_("Sale")`

2024-03-12 11:17 UTC, amarcosg commented on contract_sale_generation/models/abstract_contract.py
> -    def _selection_generation_type(self):
I tried to workaround it but the problem seems related to Selection translations in Abstract model, which is the case. https://github.com/odoo/odoo/issues/64065

Taking that in account for me the change is OK

2024-03-12 11:18 UTC, amarcosg approved these changes
LGTM

2024-03-12 11:28 UTC, flalexg commented
Functional Review. LGTM.
![image](https://github.com/OCA/contract/assets/126599115/244c7faf-b6fc-4726-a502-3efa84d3a8c3)
![image](https://github.com/OCA/contract/assets/126599115/af7ec600-3db2-443b-a798-e20a2e24333a)

2024-03-12 11:29 UTC, flalexg approved these changes

2024-03-16 15:22 UTC, pedrobaeza approved these changes
/ocabot merge minor

2024-03-16 15:30 UTC, merged