[MIG] contract_recurring_analytic_distribution: Migration to 10.0
OCA/contract pull request #106
Opened 2017-10-17 10:52 UTC by cubells

- update files
- update manifest

cc @Tecnativa

2017-10-17 20:20 UTC, pedrobaeza requested changes

2017-10-17 20:20 UTC, pedrobaeza commented on contract_recurring_analytic_distribution/__manifest__.py
> +    'website': 'https://github.com/OCA/contract/',
Please include now the company name in the README then as follows:
```rst
Contributors
============

* Tecnativa (https://www.tecnativa.com)
  * Pedro M. Baeza <...>
  * Vicent Cubells <....>
```

2017-10-17 20:20 UTC, pedrobaeza commented on contract_recurring_analytic_distribution/models/account_analytic_invoice_line.py
> -from openerp import models, fields, api
Just rename the file to `account_analytic_account` instead of moving part of it, as the main object is that one.

2017-11-23 00:22 UTC, pedrobaeza commented
@cubells please check Travis status

2017-11-28 23:31 UTC, pedrobaeza commented
@cubells please fix this

2017-12-02 17:56 UTC, pedrobaeza commented
Please rebase on current 10.0 that is green

2017-12-21 14:13 UTC, pedrobaeza commented
@cubells please attend this

2017-12-28 09:55 UTC, cubells commented
done @pedrobaeza !

Error is unrelated to pr I think. It's a timeout error.

2017-12-28 12:39 UTC, pedrobaeza commented
@luismontalba please review in old runbot (http://3313573-106-b9d36b.runbot1.odoo-community.org/?db=3313573-106-b9d36b-all) - new is for greenify Travis -.

2017-12-28 14:37 UTC, luismontalba approved these changes
Tested on runbot

2017-12-28 15:31 UTC, pedrobaeza approved these changes

2017-12-28 15:43 UTC, pedrobaeza commented
@cubells FYI, when a test prints a document (using wkhtmltopdf), all tests in the same repo must:

* Not use `SavepointCase`. It's a pity because setup method is executed for each test, but no other solution...
* Be executed at the end (with `@common.at_install(False)` and `@common.post_install(True)`. This sometimes can be avoided, but not always.

2017-12-28 15:46 UTC, cubells commented
@pedrobaeza 

thanks a lot!

2017-12-28 15:47 UTC, merged