[18.0][MIG][REF] split contract module into: contract, contract_line_successor, contract_termination
OCA/contract pull request #1136
Opened 2024-11-04 14:00 UTC by sbejaoui

- Standard migration to 18.0
- Remove abstract.contract.mixin and abstract.contract.line.mixin, and replace them with direct inheritance from contract.template and contract.template.line
- Extract the contract line life cycle into a new module contract_line_successor
- Extract the contract termination feature into a new module contract_termination
- Fix contract portal pages
- Clean up the UI and improve UX

![image](https://github.com/user-attachments/assets/91001ad7-4a30-4299-9464-21f50033eb0a)

![image](https://github.com/user-attachments/assets/d92644d0-a769-4558-95c4-725e8cab790c)

![image](https://github.com/user-attachments/assets/61d9314c-be6a-482c-a73a-384b7ed4f12b)

![image](https://github.com/user-attachments/assets/ffc0a2d6-22e9-432d-9d19-b3033a06ff0d)

2024-11-04 14:37 UTC, pedrobaeza commented
I think we should wait till #1134

2024-11-04 14:51 UTC, sbejaoui commented
> I think we should wait till #1134

Totally agree. I opened this PR because I needed the contract stack for a poc

2024-12-05 09:58 UTC, victoralmau commented
Please, cherry-pick https://github.com/OCA/contract/pull/1156 to commit history.

2025-01-07 16:50 UTC, victoralmau commented
Please, cherry-pick https://github.com/OCA/contract/pull/1169 to commit history.

2025-01-10 07:06 UTC, victoralmau commented
Please, cherry-pick https://github.com/OCA/contract/pull/1175 to commit history.

2025-01-17 10:36 UTC, ArnauCForgeFlow commented
Hello @pedrobaeza @sbejaoui any updates here? From what I see, this https://github.com/OCA/contract/pull/1134 doesn’t seem like it’ll be finished anytime soon. Could the migration be completed without it?

2025-01-17 10:40 UTC, pedrobaeza commented
This PR is draft also. My intention is to check the refactoring this month.

2025-02-01 11:04 UTC, pedrobaeza commented
This PR should be taken into account if this PR continues: #1190

2025-03-10 14:54 UTC, acsonefho requested changes

2025-03-10 14:54 UTC, acsonefho commented on contract/models/abstract_contract.py
> +            journal = AccountJournal.search(domain, limit=1)
[IMP] Ideally this `search` should be done before the loop and then use a `filtered(...)` to retrieve what is necessary.

2025-03-10 14:54 UTC, acsonefho commented on contract/models/account_move.py
> +class AccountMoveLine(models.Model):
[IMP] Ideally, this should be into a dedicated file

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract.py
> +                        (0, 0, {"date": date_start, "description": _("Contract start")})
Ideally, this should use the new syntax with `Command.create(...)`

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract.py
> +            rec.invoice_count = len(rec._get_related_invoices())
IMO This should be improved for a computed field.
On a large DB with many contracts + many invoices (and lines), this may cost a lost about perf.
But as `_get_related_invoices(...)` is used more than once, it should probably be done into a dedicated improvement PR.

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract.py
> +        for company in companies:
FYI you have this:
```
from odoo import tools
...
for company_id, record_group in tools.groupby(self, key=lambda r: r.company_id):
    ...
```

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract_line.py
> +                        domain.insert(0, "|")
IMP: it should be better to use `expression.OR` for better readability

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract_line.py
> +                    domain.insert(0, "|")
Same here

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract_line.py
> +        # FIXME: Change method name according to real updated field
IMP: Maybe create the new function and mark this one as deprecated

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract_line.py
> +        new_vals = self.read()[0]
The best is to use `self.copy_data()`

2025-03-10 14:54 UTC, acsonefho commented on contract/models/contract_recurrency_mixin.py
> +class ContractRecurrencyMixin(models.AbstractModel):
Should be splitted into 2 differents files

2025-03-10 14:54 UTC, acsonefho commented on contract/security/contract_security.xml
> +        <field name="groups" eval="[(4, ref('base.group_portal'))]" />
New syntax

2025-03-10 14:54 UTC, acsonefho commented on contract/security/contract_security.xml
> +            (4,ref('account.group_account_invoice'))]"
New syntax

2025-03-10 14:54 UTC, acsonefho commented on contract/security/groups.xml
> +        <field name="implied_ids" eval="[(4, ref('account.group_account_invoice'))]" />
New syntax

2025-03-14 12:16 UTC, rousseldenis commented
@sbejaoui Still draft ?

2025-04-18 15:18 UTC, sbejaoui commented
ready for review 

cc/ @manuelregidor , @pedrobaeza , @Rad0van , @ArnauCForgeFlow, @rousseldenis , @acsonefho , @qgroulard , @marielejeune

2025-04-18 15:21 UTC, sbejaoui commented on contract/models/abstract_contract.py
> +            journal = AccountJournal.search(domain, limit=1)
the search depends on conract company and contract type

2025-04-18 15:32 UTC, sbejaoui commented on contract/models/contract_line.py
> +        new_vals = self.read()[0]
in this case we need an exact copy, copy_data exclude fields marked copy=False

2025-04-21 14:22 UTC, sbejaoui commented
/ocabot migration contract

2025-04-22 06:54 UTC, marielejeune reviewed
Nice work 😎 Minor comments only

2025-04-22 06:54 UTC, marielejeune commented on contract/views/contract_line.xml
> -    <!-- TODO: Delete this view in migration to v13 or further migrations -->
Do you remember why this comment and if this view should be deleted?

2025-04-22 06:54 UTC, marielejeune commented on contract/views/contract.xml
> +
Why is this field needed? In v18 no need to add it in the view if it is only for an invisible/readonly domain.

2025-04-22 06:54 UTC, marielejeune commented on contract/views/contract.xml
> +                </attribute>
Even if it is correct here, I would prefer using `base_view_inheritance_extension` for better extension mechanisms (if some context keys are added at the same place in another addon for eg): https://github.com/OCA/server-tools/tree/18.0/base_view_inheritance_extension

2025-04-22 11:44 UTC, pedrobaeza commented
Please include #1229

2025-04-22 18:22 UTC, CRogos reviewed
I think some of the commits can be merged into the [MIG] commit?

Squash administrative commits (if any) with the previous commit for reducing commit noise. Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate for details.

2025-04-22 18:22 UTC, CRogos commented on contract/models/contract_line.py
> +        if view_type == "tree" and default_contract_type == "purchase":
shouldn't this be "list" instead of tree?

2025-04-23 09:26 UTC, CRogos requested changes

2025-04-23 09:26 UTC, CRogos commented on contract/models/contract_line.py
> +                    _(
You can replace the call to translate a string (_) with self.env._ for getting some performance improvement in some cases. See https://github.com/odoo/odoo/pull/174844.

This is only one of many occurrence of this.

2025-04-23 09:26 UTC, CRogos commented on contract/models/contract_line.py
> +                    % rec.name
maybe use this instead?

```
                    self.env._(
                        "You can't have the next invoice date before the date "
                        "of last invoice for the contract line '%(name)s'",
                        name=rec.name
                    )
```

2025-04-26 08:09 UTC, jbaudoux approved these changes
Works well for basic usage that I tested.
Thanks

2025-04-28 18:07 UTC, CRogos reviewed
I've created a new branch https://github.com/OCA/contract/pull/1230 starting from a later 17.0 and trying to make cleaner commits for a better review. Most of the changes are identical, beside minor findings like commented

![image](https://github.com/user-attachments/assets/c22e1be8-4e6c-476d-a3b3-11ec8e4b0096)

2025-04-28 18:07 UTC, CRogos commented on contract/static/src/js/contract_portal_sidebar.esm.js
> +import PortalSidebar from "@portal/js/portal_sidebar";
@odoo-modue removed

imports ordered

2025-04-29 16:24 UTC, CRogos commented on contract/static/src/js/contract_portal_tour.esm.js
> +/** @odoo-module **/
Should be removed

2025-05-06 11:26 UTC, pedrobaeza commented
Take into account #1232

2025-05-12 09:04 UTC, CRogos commented
@sbejaoui are you still working on this?

2025-05-14 07:31 UTC, sbejaoui commented
> @sbejaoui are you still working on this?

yes

2025-05-14 07:38 UTC, sbejaoui commented
> Take into account #1232

done

2025-05-19 16:45 UTC, carlos-lopez-tecnativa requested changes

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/data/mail_template.xml
> +                </div>
I think this could be a good moment to modernize this email template. Instead of including the footer here, we could just add the body and use an email layout like `mail.mail_notification_layout`.
Additional prevent rendering the button twice.

![image](https://github.com/user-attachments/assets/6d5131d0-a361-4b28-bb90-f1e182f53f22)

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract_termination/readme/CONTRIBUTORS.md
> +- Second Person <second.person@example.org> (optional company website url)
???

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/views/contract_portal_templates.xml
> +                        <th class='text-right'>Reference</th>
Please update to BS5 and check the remaining occurrences:
https://getbootstrap.com/docs/5.0/migration/#utilities

```suggestion
                        <th class='text-end'>Reference</th>
```

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/security/contract_tag.xml
> +        >['|',('company_id','=',False),('company_id','in',company_ids)]</field>
```suggestion
        >[('company_id','in',company_ids + [False])]</field>
```

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/static/src/js/contract_portal_sidebar.esm.js
> +/** @odoo-module **/
Please remove this line

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/tests/test_multicompany.py
> +                    ],
```suggestion
                    "contract_line_ids": [
                        Command.create(
                            {
                                "product_id": cls.product_1.id,
                                "name": "Services from #START# to #END#",
                                "quantity": 1,
                                "uom_id": cls.product_1.uom_id.id,
                                "price_unit": 100,
                                "discount": 50,
                                "recurring_rule_type": "monthly",
                                "recurring_interval": 1,
                                "date_start": "2018-02-15",
                                "recurring_next_date": "2018-02-22",
                            },
                        )
                    ],
```

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/views/res_partner_view.xml
> +                />
Is this necessary? From V18, Odoo adds it automatically according to this PR: https://github.com/odoo/odoo/pull/137031

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/views/res_partner_view.xml
> +                />
The same here

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/security/contract_security.xml
> +        >['|',('company_id','=',False),('company_id','in',company_ids)]</field>
Please update the domain and check the other occurrences.
```suggestion
        >[('company_id','in',company_ids + [False])]</field>
```

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract_line_successor/models/contract_line.py
> +            rec.contract_id.message_post(body=msg)
Please use Markup to render the text correctly.

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract_line_successor/models/contract_line.py
> +                        rec.contract_id.message_post(body=msg)
Please use Markup to render the text correctly.
![image](https://github.com/user-attachments/assets/a20aa9d8-283e-4d57-bd33-8a1f1c3904a3)

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract_line_successor/models/contract_line.py
> +                rec.contract_id.message_post(body=msg)
Please use Markup to render the text correctly.

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract_line_successor/models/contract_line.py
> +            rec.contract_id.message_post(body=msg)
Please use Markup to render the text correctly.
![image](https://github.com/user-attachments/assets/35d3708c-b5f5-4157-b02a-b7695607cbc9)

2025-05-19 16:45 UTC, carlos-lopez-tecnativa commented on contract/migrations/18.0.2.0.0/pre-migrate.py
I think that the new modules must be installed if they come from an older database where these fields exist. Otherwise, there could be data loss. Or should this be handled elsewhere (e.g. by OpenUpgrade)? Please clarify this.

2025-05-22 10:53 UTC, CRogos commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
```suggestion
    )
    views_to_delete = ["contract.contract_template_line_form_view"]
    for view_ref in views_to_delete:
        view = env.ref(view_ref, raise_if_not_found=False)
        if view:
            view.unlink()
```

I got an error during the upgrade that **is_auto_renew** is not part of the module. This occures duing the update of **contract_line_form_view** which references **contract_abstract_contract_line_form_view**.

2025-05-22 11:40 UTC, marielejeune commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
The problem with this migration script is that you cannot delete this view if other views inherit from it.

2025-05-22 11:42 UTC, pedrobaeza commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
But you shouldn't remove views in the middle of the migration. OpenUpgrade already avoids a hard crash on that case, and they should be removed at the end of the cycle being noupdate=0. If they are not remvoed, it's because there are manual children views, and in that case, you should fix it manually on your DB.

2025-05-22 12:57 UTC, CRogos commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
Is there a possibility to force the update of **contract_template_line_form_view** before **contract_line_form_view**  is updated? This could also fix the issue without removing/readding the contract_template_line_form_view.

2025-05-22 13:27 UTC, pedrobaeza commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
I insist: which issue? How are you "updating"?

2025-05-22 13:34 UTC, marielejeune commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
@pedrobaeza I got the same issue when launching a `click-odoo-update --update-all` on a DB that was migrated by Odoo from v12 to v18.
@CRogos I personally solved my issue by deleting all views (all entries in ir_ui_view table) before launching this big click-odoo-update, as in our case the users are not supposed to modify the views from the UI.

2025-05-22 13:54 UTC, MiquelRForgeFlow commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
FYI [delete_records_safely_by_xml_id](https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L3428 ) contains `delete_childs` parameter to delete all inheriting views of the view you want to delete.

2025-05-22 14:21 UTC, CRogos commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
@MiquelRForgeFlow solution is the best in my opinion, because everything which refers to this view should be recreated later anyway. (Anyone who is allowing to modify views in the UI can't be helped anyway 🤪 )

2025-05-22 14:26 UTC, CRogos commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
Have not tested yet:

```suggestion
    )
    views_to_delete = ["contract.contract_template_line_form_view"]
    openupgrade.delete_records_safely_by_xml_id(env, views_to_delete, True) 
```

2025-05-26 11:37 UTC, jbaudoux commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +from openupgradelib import openupgrade
add `openupgradelib` in repo requirements.txt and module manifest

2025-05-26 14:14 UTC, pedrobaeza commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +from openupgradelib import openupgrade
I don't think so. You don't need it when installing this module from scratch. It's only for migrations, and you should know that migrating, that library is required.

2025-05-29 09:53 UTC, sbejaoui commented on contract/migrations/18.0.2.0.0/pre-migrate.py
IMO, this should be handled in your project dependencies.
Devs who are migrating contract and were using the successor feature should be aware that they need to add those modules to their project dependencies.
Those who weren't using these features don't need to install the new modules—they can simply install contract.
That’s essentially the purpose of this PR.

@pedrobaeza , what do you think?

2025-05-30 14:36 UTC, carlos-lopez-tecnativa approved these changes
LGTM, just a non-blocking comment.

@pedrobaeza @victoralmau please take a look

TT55910

2025-05-30 14:36 UTC, carlos-lopez-tecnativa commented on contract/data/mail_template.xml
> +                </div>
Please review this comment

2025-05-30 14:36 UTC, carlos-lopez-tecnativa commented on contract/security/contract_tag.xml
Why are these rules and access rights defined in a separate file? Could you include them in `contract_security.xml` and `ir.model.access.csv` instead?

2025-05-30 16:00 UTC, pedrobaeza commented on contract/migrations/18.0.2.0.0/pre-migrate.py
OK for me to not handle it for the moment.

2025-06-02 08:39 UTC, rousseldenis commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +from openupgradelib import openupgrade
I would say the same as @pedrobaeza, BUT adding it to manifest is not anoying and allow to pull the dependency automatically at environment install. So, I would have added it.

2025-06-02 08:41 UTC, rousseldenis commented on contract/security/contract_tag.xml
As that's a matter of taste, I would prefer the writing of model access in an xml. So, I would have let it here.

2025-06-02 09:26 UTC, marielejeune commented on contract/models/contract_tag.py
> +        default=lambda self: self.env.company.id,
```suggestion
        default=lambda self: self.env.company,
```

2025-06-02 11:16 UTC, sbejaoui commented
@CRogos , @pedrobaeza 

I squashed the commits 

![image](https://github.com/user-attachments/assets/b243c17e-25fd-404b-bdd0-76d57d88bd47)

2025-06-02 16:16 UTC, rousseldenis commented on contract/models/contract_template.py
> +    def _onchange_contract_type(self):
@sbejaoui Why not moving to computed field for `automatic_price`?

2025-06-02 16:16 UTC, rousseldenis commented on contract/models/contract_template_line.py
> +                raise ValidationError(_("Discount should be less or equal to 100"))
Maybe mentionning the concerned line could help user.

2025-06-03 10:35 UTC, rousseldenis commented
@CRogos @acsonefho Could you check this ? Ready to be merged

2025-06-03 12:40 UTC, CRogos commented on contract/migrations/18.0.2.0.0/pre-migrate.py
> +    )
@sbejaoui could you add the above suggestion to the migration script. 

I still get this error when upgrading my database with odoo.sh.

```
2025-06-03 08:06:56,339 99 ERROR  odoo.modules.registry: Failed to load registry
2025-06-03 08:06:56,343 99 CRITICAL  odoo.service.server: Failed to initialize database ` `. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/service/server.py", line 1328, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 228, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 608, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 548, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing /home/odoo/src/user/modules/oca/contract/contract/views/contract_template_line.xml:4
Error while validating view near:

                    </group>
                    <group invisible="display_type">
                        <field name="is_auto_renew"/>
                        <field name="is_canceled" invisible="1"/>
                    </group>

Field "is_auto_renew" does not exist in model "contract.template.line"

View error context:
{'file': '/home/odoo/src/user/modules/oca/contract/contract/views/contract_template_line.xml',
 'line': 33,
 'name': 'contract.template.line form view (in contract)',
 'view': ir.ui.view(3100,),
 'view.model': 'contract.template.line',
 'view.parent': ir.ui.view(3086,),
 'xmlid': 'contract_template_line_form_view'}
```

2025-06-03 12:41 UTC, acsonefho requested changes
Minor changes :pray: 
I do my best to read everything and understand but honestly, it was huge!

Thanks for that amazing work @sbejaoui

2025-06-03 12:41 UTC, acsonefho commented on contract/models/contract.py
> +    @api.model
Incorrect `api.model`

2025-06-03 12:41 UTC, acsonefho commented on contract/models/contract.py
> +    @api.model
Incorrect `api.model`

2025-06-03 12:41 UTC, acsonefho commented on contract/models/abstract_contract_line.py
Should be removed?

2025-06-03 12:41 UTC, acsonefho commented on contract/models/contract_template.py
> +            domain = [
This should be executed before the loop to do a single search :pray:

2025-06-03 12:41 UTC, acsonefho commented on contract_line_successor/models/contract_line.py
> +        if state == "in-progress":
The best for readability is to refactor this using `expression.AND/OR(...)`.
To split them into smaller domain.

2025-06-04 08:48 UTC, peluko00 requested changes

2025-06-04 08:48 UTC, peluko00 commented on contract/models/contract.py
> +from odoo.tools.translate import _
Use `self.env._` please according to this commit https://github.com/odoo/odoo/pull/174844

2025-06-04 08:48 UTC, peluko00 commented on contract/models/contract_line.py
> +from odoo import _, api, fields, models
Same with translations here

2025-06-04 08:48 UTC, peluko00 commented on contract/models/contract_recurring_mixin.py
> +        readonly=True,
Refactor readonly into views

2025-06-04 08:52 UTC, rousseldenis commented on contract/models/contract_recurring_mixin.py
> +        readonly=True,
Could you elaborate ?

2025-06-04 08:56 UTC, rousseldenis commented on contract/models/contract_template.py
> +            domain = [
The problem with that is you will probably retrieve more than needed journals per company. I'll let that as is for the moment as you usually don't create contracts in batch.

2025-06-04 09:50 UTC, peluko00 commented on contract/models/contract_recurring_mixin.py
> +        readonly=True,
Refactor declared fields with `readonly=True` to the differents views with this fields with `readonly="1"`

2025-06-04 09:56 UTC, CRogos commented on contract/models/contract_recurring_mixin.py
> +        readonly=True,
@rousseldenis I think @peluko00 refers to a step of v17 migration guide.
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

-If a field is marked as readonly=True on the model, it won't be possible to import it through the Odoo import tool, so avoid it as possible and define the readonly attribute on the views instead.

2025-06-04 09:59 UTC, peluko00 commented on contract/models/contract_recurring_mixin.py
> +        readonly=True,
Yes, this is the idea. Thank you @CRogos !

2025-06-04 10:03 UTC, rousseldenis commented on contract/models/contract_recurring_mixin.py
> +        readonly=True,
@peluko00 @CRogos It's intended. We should not allow to import contract with that value.

To help updating this field, we should use: https://github.com/OCA/contract/tree/14.0/contract_update_last_date_invoiced

2025-06-04 10:04 UTC, rousseldenis commented on contract_line_successor/models/contract_line.py
> +        if state == "in-progress":
@acsonefho We shall do that in a further PR. As the `get_state_domain()` function result is also updated. A little too tricky to do it here.

2025-06-04 10:05 UTC, rousseldenis commented
@acsonefho Could you update your review ?

2025-06-04 10:36 UTC, rousseldenis commented
@peluko00 Could you update your review ?

2025-06-04 11:11 UTC, acsonefho approved these changes

2025-06-04 11:29 UTC, rousseldenis commented
All comments have been adressed !

Let's go

/ocabot merge nobump

2025-06-04 11:37 UTC, merged

2025-06-04 16:04 UTC, CRogos commented
I think this was not finally addressed: https://github.com/OCA/contract/pull/1248