[10.0][IMP] Add display sequence on contract lines
OCA/contract pull request #119
Opened 2017-11-11 19:23 UTC by pedrocasi

A simple improvement to allows users to reorder the contract lines.

2017-11-12 03:58 UTC, carlosdauden requested changes
Change version number

2017-11-13 09:51 UTC, pedrocasi commented
Current version is 10.0.3.0.0. Should I bump it to 10.0.3.0.1 or 10.0.3.1.0?

2017-11-14 12:29 UTC, carlosdauden commented
At least 10.0.3.1.0

https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

2017-11-17 18:44 UTC, pedrocasi commented
Thank you for the info. The PR has been updated.

2017-11-17 19:50 UTC, pedrobaeza approved these changes
Squashing on merge

2017-11-17 20:13 UTC, lasley approved these changes
Great improvement, thanks @pedrocasi. One comment inline, minor

2017-11-17 20:13 UTC, lasley commented on contract/models/account_analytic_invoice_line.py
> +        help="Sequence of the contract line when displaying contracts"
Please add trailing comma

2017-11-18 09:40 UTC, carlosdauden approved these changes

2017-11-18 18:25 UTC, merged