[11.0] [MIG] contract show invoice
OCA/contract pull request #148
Opened 2018-02-17 14:42 UTC by levkar

2018-03-09 08:22 UTC, feketemihai commented
@levkar Please squash transifex commits..

2018-03-09 08:22 UTC, feketemihai requested changes

2018-03-09 08:22 UTC, feketemihai commented on contract_show_invoice/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
@levkar Please update readme, images with png, Odoo version in runbot..

2018-03-26 15:40 UTC, pedrobaeza commented
This module is for showing invoices not generated by contracts, but having the analytic account, so I would change the name of the module and also move the module to OCA/account-analytic.

2018-03-30 12:32 UTC, levkar commented
I agree. I was wondering why it is in contracts :)

2018-04-01 17:17 UTC, pedrobaeza commented
Closing then.

2018-04-01 17:17 UTC, closed without merging