[ADD] [MIG] agreement_legal migration
OCA/contract pull request #301
Opened 2019-03-29 16:14 UTC by ygol

2019-04-01 10:26 UTC, murtuzasaleh requested changes

2019-04-01 10:26 UTC, murtuzasaleh commented on agreement_legal/models/agreement.py
> +    payment_term_id = fields.Many2one(
@ygol There is no `account` module dependency in the manifest file.

2019-04-01 10:26 UTC, murtuzasaleh commented on agreement_legal/__manifest__.py
> +    "depends": ["contacts", "agreement", "mail", "product"],
@ygol No need for `mail` module in dependency because it is already in the `contacts` module.

2019-04-02 14:50 UTC, max3903 approved these changes

2019-04-02 14:57 UTC, osi-scampbell approved these changes

2019-04-02 15:04 UTC, murtuzasaleh approved these changes

2019-04-02 15:07 UTC, merged