11.0 mig contract sale generation
OCA/contract pull request #329
Opened 2019-05-14 10:59 UTC by sylvainvh

Migration of module contract_sale_generation

I added the field contract_id on sale.order to replace the previous field journal_id

2019-05-15 17:55 UTC, tbaden requested changes
thanks for the work 👍 
I did a code review: LGTM,
but please use the new fragment [readme](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0)
plus some optional changes if you like.

2019-05-15 17:55 UTC, tbaden commented on contract_sale_generation/data/contract_cron.xml
> +    <record model="ir.cron" id="account_analytic_cron_for_sale">
optional change:
id before model

2019-05-15 17:55 UTC, tbaden commented on contract_sale_generation/views/sale_view.xml
> +    <record id="act_recurring_sales" model="ir.actions.act_window">
optional change:
action id pattern

> For an action: the main action respects <model_name>_action. Others are suffixed with _<detail>, where detail is an underscore lowercase string explaining the action (should not be long). This is used only if multiple actions are declared for the model.

2019-05-15 17:55 UTC, tbaden commented on contract_sale_generation/views/account_analytic_account_view.xml
> +    <record id="account_analytic_account_recurring_sale_form" model="ir.ui.view">
optional change:
use original id (account_analytic_account_recurring_form_form)

2019-05-20 11:19 UTC, luismontalba approved these changes
Tested on runbot

2019-05-20 15:10 UTC, sylvainvh commented
Hi @tbaden , @pedrobaeza and @luismontalba . I made required changes on my PR.

2019-05-20 15:16 UTC, tbaden requested changes

2019-05-20 15:16 UTC, tbaden commented on contract_sale_generation/readme/USAGE.rst
> +   :alt: Try me on Runbot
Runbot Button gets generated. Please remove this part from usage

2019-05-20 15:22 UTC, tbaden approved these changes
LGTM, please squash your commits into one. Thanks 👍

2019-05-20 15:29 UTC, tbaden requested changes
Sorry, noticed you removed it from readme instead of usage. Readme gets generated by oca bot. You have to change the usage.rst

2019-05-27 15:00 UTC, rafaelbn commented
Hello, this PR is duplicated there is a migrationg before in https://github.com/OCA/contract/pull/320 made by @Bilbonet

2019-09-10 05:27 UTC, rafaelbn commented
As I said this PR is duplicated. We should review previous one https://github.com/OCA/contract/pull/320

2019-12-17 00:08 UTC, pedrobaeza commented
/ocabot merge

2019-12-17 00:18 UTC, pedrobaeza commented
/ocabot merge

2019-12-17 00:28 UTC, flotho requested changes

2019-12-17 00:28 UTC, flotho commented on contract_sale_generation/models/account_analytic_account.py
> +            'price_unit': line.price_unit,
In this part we're missing UOM . Is it possible to add this part https://github.com/OCA/contract/pull/284/files

2019-12-17 08:56 UTC, pedrobaeza commented
@sylvainvh can you attend @flotho's comment?

2019-12-30 14:16 UTC, flotho commented
Hi @sylvainvh , any chance to have a review ?

Regards

2019-12-30 14:56 UTC, flotho commented
Hi, @pedrobaeza ,

I propose a merge and I will propose a PR.

2020-03-11 21:25 UTC, flotho commented
Hi @sylvainvh 

Any chance to have a review on my PR on your repo ?
@pedrobaeza , do you recommend me to propose the same PR from https://github.com/sylvainvh/contract/pull/1 ?

2020-03-12 07:53 UTC, pedrobaeza commented
If @sylvainvh doesn't answer in a while, you can supersede this PR with a new one starting from this and adding your extra commit.

2021-12-19 12:14 UTC, closed without merging