ADD more markers #START_MONTH# and #END_MONTH#
OCA/contract pull request #41
Opened 2016-11-13 19:50 UTC by gonxi

2016-11-13 19:56 UTC, pedrobaeza requested changes
Remove 'text' word in your additions.

2016-11-13 20:09 UTC, gonxi commented
ok!

2016-12-05 17:53 UTC, StefanRijnhart commented
How about allowing for a template string passed to strftime instead of adding more and more custom substitutions?

2016-12-05 18:42 UTC, lasley commented
I second that idea. Playing off the current format, we could just embed the string into the markers. Maybe something like `#START:%B %Y#`, then just split by `:` & use the internal date format if included. Otherwise fallback to format in arg in order to provide back compatibility.

2017-01-29 03:29 UTC, ovnicraft commented
@StefanRijnhart i start working with `contract` module so you recomendation will have locale issue ? so `strftime`  so `datetime` is locale aware but IDK about `strftime`

2017-01-30 16:20 UTC, lasley commented
@ovnicraft - By locale, do you mean the ability to put months in as different languages?

2017-01-31 09:41 UTC, elicoidal commented on contract_recurring_invoicing_marker/__openerp__.py
> +    'author': 'Serv. Tecnol. Avanzados - Pedro M. Baeza, bisnesmart - Gonzalo Borrás,'
usually we put companies in that section as the contributors are in the README

2017-01-31 09:49 UTC, pedrobaeza commented on contract_recurring_invoicing_marker/__openerp__.py
> +    'author': 'Serv. Tecnol. Avanzados - Pedro M. Baeza, bisnesmart - Gonzalo Borrás,'
Yeah, the exception was me, that my name was my company. But this is no more, as we have now Tecnativa, so the correct is: `Tecnativa, bisnesmart,`

2017-01-31 09:51 UTC, pedrobaeza commented on contract_recurring_invoicing_marker/__openerp__.py
> +    'author': 'Serv. Tecnol. Avanzados - Pedro M. Baeza, bisnesmart - Gonzalo Borrás,'
Anyway, I'm not sure if this contribution is enough to raise Gonzalo as co-author. @lasley mentioned an interesting rule: if the contribution is about 20-30% of new/refactored code, it deserves to be here. If not, then it should go to contributors section on README.

2017-01-31 16:34 UTC, lasley commented on contract_recurring_invoicing_marker/__openerp__.py
> +    'author': 'Serv. Tecnol. Avanzados - Pedro M. Baeza, bisnesmart - Gonzalo Borrás,'
Keep in mind that the author key is a limited field, and I'm pretty sure it's not even the full 255 chars of the field.

I'll submit a draft change to our contribution guidelines today on this. I've been testing the rule internally, but quite a few heavy contributors seemed to like it when they saw it. Figure it's time to make the suggestion official now that it's public 😄

2017-01-31 18:35 UTC, gonxi commented on contract_recurring_invoicing_marker/__openerp__.py
> +    'author': 'Serv. Tecnol. Avanzados - Pedro M. Baeza, bisnesmart - Gonzalo Borrás,'
For me it is not a problem to appear here or in the readme. I only added my name by convention

2017-01-31 19:28 UTC, StefanRijnhart commented
@ovnicraft Good point. Maybe use Babel's format_date instead. http://babel.pocoo.org/en/latest/dates.html

2017-05-06 22:36 UTC, rafaelbn commented
Hi @gonxi , please could you review travis in order to get it green? 😄

2017-12-02 15:48 UTC, pedrobaeza commented
Any news about this. If requested changes are not performed, I will proceed to close it for cleaning this.

2018-03-26 15:36 UTC, pedrobaeza commented
Closing as no further answer.

2018-03-26 15:36 UTC, closed without merging