[MIG] contract_payment_auto: Migration from 10.0 to 12.0
OCA/contract pull request #448
Opened 2019-12-21 17:53 UTC by norlinhenrik

I need contract_payment_auto for 12.0. [How can I use this with e.g. Stripe?](https://odoo-community.org/groups/contributors-15/contributors-151468) Is there a way in Odoo community to let customers start a subscription/contract? Then the contract would recurringly generate invoices and automatic payments with e.g. Stripe.

I have NOT written any migration scripts.

All tests were disabled in [10.0](https://github.com/OCA/contract/blob/10.0/contract/__init__.py). 
I have enabled the tests, and disabled some tests because "The ['Test Acquirer'] payment acquirers are not allowed to manual capture mode!"

2019-12-21 18:43 UTC, norlinhenrik commented
I did one functional change on the field is_auto_pay: default=False

2019-12-23 04:23 UTC, nikul-serpentcs reviewed
minor change

2019-12-23 04:23 UTC, nikul-serpentcs commented on contract_payment_auto/__manifest__.py
> +    "website": "https://laslabs.com",
@norlinhenrik URL Should be https://github.com/OCA/contract

2019-12-26 14:05 UTC, brian10048 requested changes

2019-12-26 14:05 UTC, brian10048 commented on contract_payment_auto/__init__.py
> +from . import tests
```suggestion
```
Not required to run tests

2019-12-26 14:05 UTC, brian10048 commented on contract_payment_auto/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Can you separate the README sections into their own files in a README directory [as described here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration)

2020-07-15 14:05 UTC, chafique-delli commented
@norlinhenrik , can you :
- apply the changes suggested above
- check travis CI why it's failed
Thanks.

2020-07-19 08:55 UTC, norlinhenrik commented
[https://github.com/OCA/contract/blob/12.0/contract_variable_qty_timesheet/tests/test_contract_variable_qty_timesheet.py#L49](https://github.com/OCA/contract/blob/12.0/contract_variable_qty_timesheet/tests/test_contract_variable_qty_timesheet.py#L49)
`contract._recurring_create_invoice(date_ref)`
Why does [Travis](https://travis-ci.org/github/OCA/contract/jobs/709310827#L2040) give this ERROR?
`_recurring_create_invoice() takes 1 positional argument but 2 were given`

2020-07-20 13:13 UTC, chafique-delli reviewed
@norlinhenrik , fixes to be made in the test_contract.py file:
contract_payment_auto/tests/test_contract.py:10:1: F401 'odoo.tools.mute_logger' imported but unused
contract_payment_auto/tests/test_contract.py:13:1: F401 '..models.contract' imported but unused
contract_payment_auto/tests/test_contract.py:77:5: E303 too many blank lines (2)
contract_payment_auto/tests/test_contract.py:121:5: E303 too many blank lines (2)
contract_payment_auto/tests/test_contract.py:208:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:209:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:213:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:214:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:220:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:221:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:228:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:229:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:230:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:245:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:246:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:247:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:255:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:256:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:264:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:265:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:274:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:275:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:312:5: E265 block comment should start with '# '
contract_payment_auto/tests/test_contract.py:312:89: E501 line too long (105 > 88 characters)
contract_payment_auto/tests/test_contract.py:313:5: E265 block comment should start with '# '

2020-07-20 13:13 UTC, chafique-delli commented on contract_payment_auto/models/contract.py
> +    def _recurring_create_invoice(self):
replace '_recurring_create_invoice' by 'recurring_create_invoice' method

2020-07-20 13:13 UTC, chafique-delli commented on contract_payment_auto/tests/test_contract.py
> +        invoice = self.contract._recurring_create_invoice()
replace '._recurring_create_invoice()' by '.recurring_create_invoice()' method

2020-07-20 13:13 UTC, chafique-delli commented on contract_payment_auto/tests/test_contract.py
> +            invoice = self.contract._recurring_create_invoice()
replace '._recurring_create_invoice()' by '.recurring_create_invoice()' method

2020-07-20 13:13 UTC, chafique-delli commented on contract_payment_auto/tests/test_contract.py
> +            invoice = self.contract._recurring_create_invoice()
replace '._recurring_create_invoice()' by '.recurring_create_invoice()' method

2020-07-22 05:38 UTC, norlinhenrik commented on contract_payment_auto/models/contract.py
> +    def _recurring_create_invoice(self):
Instead I have added `date_ref=False`

2020-07-25 10:36 UTC, chafique-delli approved these changes

2020-07-27 16:20 UTC, brian10048 approved these changes

2020-08-27 07:02 UTC, fcayre commented
I faced and fixed several problems while testing the module port to 12.0:
- permissions for payment tokens and transactions are missing: no one can use the "Create invoices" button as only the owner of a token and transaction is allowed to read the token / transaction
- the contract module returns several invoices in _recurring_create_invoice, which makes your implementation crash; even more serious is that the returned invoices can be issued from different contracts which is_auto_pay attribute may be different and there is no more a relation from one invoice to its contract to find out the is_auto_pay value applicable to the invoice...

2022-01-31 11:47 UTC, legalsylvain commented
Hi @norlinhenrik. What is the state of this PR ? could you take a look on @fcayre comment ? 
kind regards.

2022-06-18 11:01 UTC, rousseldenis commented
@norlinhenrik Could we switch to #798 and close this ?

2022-06-20 11:00 UTC, ghost commented
@rousseldenis Yes sure!

2022-06-20 11:35 UTC, closed without merging