[12.0][FIX+IMP] - get fiscal position according to contract company + use get_fiscal_position
OCA/contract pull request #540
Opened 2020-08-17 16:33 UTC by sbejaoui

2020-08-17 18:41 UTC, pedrobaeza requested changes
The same apply to payment_term_id

2020-08-18 07:30 UTC, pedrobaeza approved these changes

2020-08-18 07:53 UTC, pedrobaeza commented on contract/models/contract.py
> +            else self.partner_id.with_context(force_company=company_id)
```suggestion
            else self.partner_id.with_context(force_company=self.company_id)
```

2020-08-18 08:19 UTC, pedrobaeza approved these changes

2020-08-19 00:14 UTC, marcelsavegnago approved these changes

2020-08-20 08:05 UTC, dreispt commented
/ocabot merge patch

2020-08-20 09:00 UTC, merged