[13.0][MIG] agreement
OCA/contract pull request #628
Opened 2021-02-14 16:46 UTC by sergio-teruel

cc @Tecnativa TT27165

Superseeds PR https://github.com/OCA/contract/pull/578 without name changed.

2021-02-14 17:47 UTC, sergio-teruel commented
Runbot display fail but is runing... why??

2021-02-14 20:54 UTC, pedrobaeza commented
See the video to know how to get to the problem:

https://user-images.githubusercontent.com/7165771/107888848-3471d500-6f0f-11eb-8231-9b3901b825ac.mp4

2021-02-15 10:37 UTC, carlosdauden approved these changes

2021-02-15 17:27 UTC, pedrobaeza requested changes
It seems the migration commit contains black/prettier formatting. Can you please isolate that one so it's not contaminated with it and the review is done more accurately?

2021-02-15 17:27 UTC, pedrobaeza commented on agreement/security/agreement_security.xml
> +        >['|', ('company_id', '=', False), ('company_id', 'child_of', [user.company_id.id])]</field>
This rule must be transformed and migration scripts should be added. See in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 the line about that.

2021-02-15 20:03 UTC, pedrobaeza approved these changes

2021-02-15 20:03 UTC, pedrobaeza commented
/ocabot merge nobump

2021-02-15 20:22 UTC, marcelsavegnago approved these changes

2021-02-15 20:44 UTC, merged