[MIG] 14.0 agreement_sale
OCA/contract pull request #655
Opened 2021-03-15 10:40 UTC by PierrickBrun

2021-05-10 21:29 UTC, patrickrwilson requested changes
Just a few requested changes.
- no longer needed xml lines
- tracking_visibility change

2021-05-10 21:29 UTC, patrickrwilson commented on agreement_sale/models/sale.py
> +        track_visibility="onchange",
v13 changed the track_visibility attribute and it should now be tracking=True.

2021-05-10 21:29 UTC, patrickrwilson commented on agreement_sale/models/sale.py
> +        track_visibility="onchange",
v13 changed the track_visibility attribute and it should now be tracking=True

2021-05-10 21:29 UTC, patrickrwilson commented on agreement_sale/views/agreement.xml
> +<?xml version="1.0" ?>
This line is no longer needed.

2021-05-10 21:29 UTC, patrickrwilson commented on agreement_sale/views/res_config_settings.xml
> +<?xml version="1.0" encoding="utf-8" ?>
This line is no longer needed.

2021-05-10 21:29 UTC, patrickrwilson commented on agreement_sale/views/sale_order.xml
> +<?xml version="1.0" encoding="utf-8" ?>
This line is no longer needed.

2021-05-20 08:39 UTC, PierrickBrun commented
@patrickrwilson Done and rebased.

I will need someone to approve the workflow but idk who to ping

2021-05-20 14:18 UTC, patrickrwilson approved these changes
The only thing left that you should squash the [UPD] and translation commits to clean up the commit history and remove all the automated commits. 

Other than that it looks good.

2021-05-20 14:20 UTC, patrickrwilson commented
@max3903 @dreispt @osi-scampbell @ReedHayashikawa can you help review please?

2021-06-16 09:25 UTC, rconjour approved these changes
LGTM

2021-06-28 21:55 UTC, smangukiya approved these changes
LGTM

2021-07-01 15:20 UTC, max3903 commented
/ocabot merge nobump

2021-07-01 15:57 UTC, merged