[MIG] contract_payment_mode: Migration to 10.0
OCA/contract pull request #71
Opened 2017-05-25 08:50 UTC by chienandalu

Minor migration tweaks

cc @Tecnativa

2017-05-25 11:40 UTC, pedrobaeza requested changes
And add the dependency on oca_repositories.txt to bank-payment

2017-05-25 11:40 UTC, pedrobaeza commented on contract_payment_mode/__init__.py
> +# Copyright 2016 Antiun Ingenieria S.L. - Antonio Espinosa
Remove copyright here

2017-05-25 16:19 UTC, pedrobaeza commented on contract_payment_mode/oca_dependencies.txt
> +bank-payment
oca_dependencies.txt file should be in the root, not here.

2017-05-25 20:04 UTC, pedrobaeza commented
@tedsalmon @lasley your mock patch in https://github.com/OCA/contract/blob/10.0/product_contract/tests/test_sale_order.py is provoking that our tests fail: https://travis-ci.org/OCA/contract/jobs/236107899#L805. Please unpatch correctly on your tearDown (it's not automatically undone as this is not a DB transaction)

2017-06-01 15:38 UTC, lasley commented
@pedrobaeza - why close ths?

2017-06-01 15:42 UTC, pedrobaeza commented
Sorry, my fault

2017-06-02 08:29 UTC, chienandalu commented
@pedrobaeza  It's all green now

2017-06-06 15:57 UTC, pedrobaeza requested changes

2017-06-06 15:57 UTC, pedrobaeza commented on contract_payment_mode/models/contract.py
> +    def _prepare_invoice_data(self, contract):
As we have seen on v9, this method is incorrect. Correct one is `_prepare_invoice` (see https://github.com/OCA/contract/pull/73/files#diff-237fb5082150850f78bb85c3c23bf563R20)

2017-06-06 15:57 UTC, pedrobaeza commented on contract_payment_mode/tests/test_contract_payment.py
> +        res = self.contract._prepare_invoice_data(self.contract)
Test shouldn't call directly this method, but check result on the invoice after calling `recurring_create_invoice`. Check https://github.com/OCA/contract/pull/73/files#diff-fad070bd2b05e275bf84e1c69de78209L72

2017-06-09 08:14 UTC, chienandalu commented
@pedrobaeza Changes done and green already

2017-06-09 09:52 UTC, pedrobaeza approved these changes

2017-06-09 09:53 UTC, pedrobaeza commented
@rafaelbn please review

2017-06-12 14:28 UTC, rafaelbn approved these changes
Tested in runbot 👍

2017-06-12 14:35 UTC, merged