[14.0] new addon contract_sequence
OCA/contract pull request #820
Opened 2022-05-04 08:09 UTC by scigghia

This addon adds sequence to contract and contract template
it sets also a default sequence for contract in company settings

2022-05-06 09:37 UTC, angelmoya commented
Tested on runboat, I can not create a customer contract.

2022-05-06 16:40 UTC, scigghia commented
thank you for your feedback @angelmoya i fixed some default values and now should be fine
but i think runboat for this pr is broken

2022-05-07 10:20 UTC, scigghia commented
@sbidoul could you take a look to the runboat please?

2022-05-07 10:48 UTC, sbidoul commented
likely due to this: https://github.com/OCA/oca-ci/issues/29

2022-05-14 14:04 UTC, scigghia commented
@angelmoya did you have the opportunty to test? now the runboat is running :)

2022-05-16 09:30 UTC, angelmoya commented
Nice, is working right... but codecov is to low.. if you can add tests would be great

2022-05-21 12:36 UTC, scigghia commented
why travis and runboat are crashing on account_banking_mandate ?
@sbidoul

2022-05-21 13:57 UTC, sbidoul commented
That was an expired certificate on odoo-community.org again. It's resolved now please retry.

2022-05-21 14:06 UTC, scigghia commented
> That was an expired certificate on odoo-community.org again. It's resolved now please retry.

thank you @sbidoul

2022-10-10 08:21 UTC, scigghia commented
no one interested in this module?

2022-10-10 08:32 UTC, rousseldenis commented
/ocabot rebase

2022-10-10 08:37 UTC, rousseldenis requested changes

2022-10-10 08:37 UTC, rousseldenis commented on contract_sequence/__manifest__.py
> +    "version": "14.0.0.0.1",
```suggestion
    "version": "14.0.1.0.0",
```

2022-10-10 08:37 UTC, rousseldenis commented on contract_sequence/models/contract.py
> +            raise UserWarning(_("No default sequence found!"))
Please raise Odoo exception (UserError)

2022-10-10 08:37 UTC, rousseldenis commented on contract_sequence/models/contract.py
> +    sequence_id = fields.Many2one(
Please put fields definition on top

2022-10-10 08:37 UTC, rousseldenis commented on contract_sequence/models/contract.py
> +        default=get_default_sequence,
Please use lambda

2022-10-10 08:37 UTC, rousseldenis commented on contract_sequence/models/contract_template.py
> +    _inherit = "contract.template"
Is the sequencing wanted on templates ?

2022-10-10 08:37 UTC, rousseldenis commented on contract_sequence/tests/test_contract_sequence.py
> +class TestContractSequence(TransactionCase):
Please use SavepointCase

2023-04-02 12:15 UTC, closed without merging