[14.0][FIX] Add check_company=True on contracts and contract lines
OCA/contract pull request #821
Opened 2022-05-09 12:36 UTC by alexis-via

Add check_company=True in field definition and
[('company_id', '=', company_id)] in the domain (in view or in field definition)

2022-05-09 13:52 UTC, ImDiabloxx approved these changes

2022-07-05 13:51 UTC, leemannd approved these changes

2022-07-05 13:52 UTC, rousseldenis approved these changes

2022-07-05 14:57 UTC, pedrobaeza requested changes

2022-07-05 14:57 UTC, pedrobaeza commented on contract_payment_mode/models/contract.py
> +        domain="[('payment_type', '=', 'inbound'), ('company_id', '=', company_id)]",
This should have pre-commit passed

2023-02-26 22:02 UTC, alexis-via commented
Should be green and ready to merge

2023-02-27 10:19 UTC, carlosdauden approved these changes

2023-03-01 18:46 UTC, pedrobaeza commented on contract_payment_mode/models/contract.py
> +        domain="[('payment_type', '=', 'inbound'), ('company_id', '=', company_id)]",
Please pass pre-commit, or this can't be merged.

2023-07-10 09:14 UTC, leemannd commented
The pre-commit has been fixed and @pedrobaeza 's comment has been answered.

2023-07-10 09:15 UTC, leemannd commented
/ocabot merge patch

2023-07-10 09:21 UTC, merged

2023-07-10 09:22 UTC, pedrobaeza commented
Please fw-port it to upper versions.

2023-08-09 15:18 UTC, MrTango commented on contract/models/abstract_contract.py
> +        check_company=True,
this leads to an issue with the pricelists in contract, when no multi companay is used.
I can no longer choose existing lists.
Before this change it was working fine.

2023-10-20 15:26 UTC, marcelsavegnago commented on contract/models/contract.py
> +        domain="[('company_id', '=', company_id)]",
@alexis-via do you believe it is necessary to define this domain? In this case, the objective is to force a company to be defined in each payment_term? In theory, check_company would already check whether the company is false or equal to the company in the record.