[IMP][9.0] contract: Add report + send by mail
OCA/contract pull request #86
Opened 2017-08-09 19:23 UTC by cubells

This PR adds the following features to contract module:

- a report to print contract data.
- a button to send by email contract report.

When send email, information is saved in contract chatter.

cc @Tecnativa

2017-08-10 07:27 UTC, pedrobaeza requested changes
@lasley @chienandalu please review

2017-08-10 07:27 UTC, pedrobaeza commented on contract/i18n/es.po
> +msgstr "CIF/NIF:"
Only `NIF:`

2017-08-10 07:27 UTC, pedrobaeza commented on contract/__manifest__.py
> +        'data/contract_template.xml',
Call it `mail_template.xml`

2017-08-10 16:03 UTC, pedrobaeza approved these changes

2017-08-10 16:12 UTC, lasley requested changes

2017-08-10 16:12 UTC, lasley commented on contract/data/mail_template.xml
> +    <p>If you have any question, do not hesitate to contact us.</p>
s/question/questions

2017-08-10 16:12 UTC, lasley commented on contract/data/mail_template.xml
> +       &nbsp;&nbsp;Contract date start: ${object.date_start or ''}<br />
s/Contract date start/Contract Date Start

2017-08-10 16:12 UTC, lasley commented on contract/data/mail_template.xml
> +       &nbsp;&nbsp;Contract date start: ${object.date_start or ''}<br />
Also IMO it would be best to not show this line at all if there is not a start date, vs showing a blank date.

2017-08-10 16:12 UTC, lasley commented on contract/data/mail_template.xml
> +       &nbsp;&nbsp;Your contact: <a href="mailto:${object.user_id.email or ''}?subject=Contract%20${object.name}">${object.user_id.name}</a>
s/Your contact/Your Contact

Also- it would be best to not have this be a link if the user does not have an email.

2017-08-10 16:12 UTC, lasley commented on contract/data/mail_template.xml
> +                Phone:&nbsp; ${object.company_id.phone}
Can probably remove the `&nbsp;`

2017-08-10 16:12 UTC, lasley commented on contract/data/mail_template.xml
> +                Web :&nbsp;<a href="${object.company_id.website}">${object.company_id.website}</a>
Remove the space before the semicolon & replace the &nbsp; w/ a regular space.

2017-08-10 16:12 UTC, lasley commented on contract/models/account_analytic_account.py
> +                                    False)
Why not raising when not found? What happens when it isn't found & the `compose_form.id` is used in the action keys?

2017-08-10 16:12 UTC, lasley commented on contract/report/report_contract.xml
> +                                <strong>Date Start: </strong><p t-field="o.date_start"/>
This is inconsistent with your email, which has the data values encapsulated in `<strong>` vs the data keys as they are here. Please update one (I prefer no bold personally, but I don't use the stock reports and emails anyways so it doesn't affect me)

2017-08-10 16:12 UTC, lasley commented on contract/report/report_contract.xml
> +                                <p id="services_info"><strong>Invoice Lines</strong></p>
Maybe "Recurring Items" or "Recurring Charges" or something? These aren't invoice lines, but are instead representing the lines that will be invoiced recurrently as part of the contract

2017-08-10 21:01 UTC, cubells commented on contract/report/report_contract.xml
> +                                <strong>Date Start: </strong><p t-field="o.date_start"/>
It's the same style as invoice has.
I prefer to leave it as it is.

2017-08-16 17:17 UTC, pedrobaeza commented
@lasley please give your blessings.

2017-08-16 18:07 UTC, lasley approved these changes
Thanks @cubells!

2017-08-16 18:07 UTC, merged