[14.0][FIX] product_contract: fixes the visibility of the is_contract field in the sales order form
OCA/contract pull request #987
Opened 2023-09-13 22:01 UTC by marcelsavegnago

2023-09-13 22:02 UTC, marcelsavegnago commented
ping @douglascstd @augustodinizl @aug1804 @kaynnan

2023-09-13 22:33 UTC, douglascstd approved these changes
[FUNCTIONAL TESTE] APPROVED

From:
![image](https://github.com/OCA/contract/assets/20867090/d08bfa04-83c2-40eb-bef1-43a6c7dab327)
![image](https://github.com/OCA/contract/assets/20867090/0aae2461-af1d-496a-a98f-c3ca1b4319de)


TO:
![image](https://github.com/OCA/contract/assets/20867090/3d49797f-bbdf-49df-b819-46d01d8c6192)
![image](https://github.com/OCA/contract/assets/20867090/53eda492-3f11-45b1-bc84-1879156ffeaf)

2023-09-14 06:44 UTC, rousseldenis commented on product_contract/views/sale_order.xml
> +                <field name="is_contract" attrs="{'invisible': True}" />
In this case use :


```suggestion
                <field name="is_contract" invisible="1" />
```

2023-09-14 06:44 UTC, rousseldenis requested changes
Code review

2023-09-14 11:04 UTC, marcelsavegnago commented on product_contract/views/sale_order.xml
> +                <field name="is_contract" attrs="{'invisible': True}" />
@rousseldenis  Done

2023-09-14 11:04 UTC, rousseldenis approved these changes

2023-09-20 19:34 UTC, marcelsavegnago commented
ping @sbejaoui  @pedrobaeza

2023-09-20 20:28 UTC, pedrobaeza commented
/ocabot merge minor

2023-09-20 20:34 UTC, merged