wip
OCA/contract pull request #991
Opened 2023-09-26 09:58 UTC by ilyasProgrammer

2023-09-26 13:26 UTC, francesco-ooops commented
@carlos-domatix what do you think about tests?

@simahawk implementation of https://github.com/OCA/contract/pull/971#pullrequestreview-1639482033

2023-09-26 15:44 UTC, simahawk requested changes
Thanks a lot for the effort :)

2023-09-26 15:44 UTC, simahawk commented on subscription_oca/tests/test_subscription_oca.py
> +        cls.pricelist = cls.env["product.pricelist"].create(
```suggestion
        cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
        cls.pricelist = cls.env["product.pricelist"].create(
```

2023-09-26 15:44 UTC, simahawk commented on subscription_oca/tests/test_subscription_oca.py
> +        cls.country_id = cls.env["res.country"].search([], limit=1)
```suggestion
        cls.country = cls.env["res.country"].search([], limit=1)
```
to do for all vars that are records and not IDs

2023-09-26 15:44 UTC, simahawk commented on subscription_oca/tests/test_subscription_oca.py
> +    def test_all_subscription_oca(self):
Any major reason to have just one biiiig test?
Still better than nothing of course :)
If you don't have time, add a TODO for splitting it

2023-09-26 15:44 UTC, simahawk commented on subscription_oca/tests/test_subscription_oca.py
> +        so._compute_subscriptions_count()
compute methods should be computed automatically. IF you need need this maybe there's a problem

2023-09-26 15:44 UTC, simahawk commented on subscription_oca/tests/test_subscription_oca.py
> +        self.sub_id.cron_subscription_management()
this should go to one or more cron specific tests

2023-09-26 15:44 UTC, simahawk commented on subscription_oca/tests/test_subscription_oca.py
> +        # sale.subscription.template
testing a template? :)

2023-09-27 10:18 UTC, ilyasProgrammer commented
@simahawk Thanks for the review. Please have a look again.

2023-09-28 10:21 UTC, carlos-domatix commented
Thanks a lot for the effort. I see it well but it has 70% coverage https://app.codecov.io/gh/OCA/contract/tree/15.0-subscription_oca-tests/, I don't know if it is enough for the repo, but at least it is a good base.

2023-09-29 17:10 UTC, simahawk approved these changes

2023-09-29 17:13 UTC, simahawk commented
/ocabot merge patch

2023-09-29 17:19 UTC, merged