[15.0][MIG] contract_price_revision: Migration to version 15.0
OCA/contract pull request #992
Opened 2023-09-28 10:46 UTC by carolinafernandez-tecnativa

- Standard migration to v15
- Add ir.model.access.csv
- Fix error comparing dates

@Tecnativa

TT45292

@pedrobaeza @carlosdauden

2023-09-28 12:12 UTC, pedrobaeza commented
/ocabot migration contract_price_revision

2023-09-28 12:18 UTC, pedrobaeza requested changes

2023-09-28 12:18 UTC, pedrobaeza commented on contract_price_revision/models/contract_line.py
> +from odoo.fields import Date
No need of importing a special variable, use `fields.Date.today()` instead.

2023-09-28 12:18 UTC, pedrobaeza commented on contract_price_revision/security/ir.model.access.csv
> +access_contract_price_revision_wizard,access_contract_price_revision_wizard,model_contract_price_revision_wizard,base.group_user,1,1,1,1
You should mimic here the permissions of the contract model, not leaving this open for any internal user.

2023-09-28 12:18 UTC, pedrobaeza commented on contract_price_revision/wizards/contract_price_revision.py
> +        action = self.env["ir.actions.actions"]._for_xml_id(
Don't replace `ir.actions.act_window`

2023-09-28 17:38 UTC, pedrobaeza approved these changes

2023-10-02 08:47 UTC, carolinafernandez-tecnativa commented
ping @pedrobaeza

2023-10-10 13:49 UTC, carolinafernandez-tecnativa commented
ping @carlosdauden

2023-10-10 21:26 UTC, carlosdauden approved these changes

2023-10-10 22:25 UTC, pedrobaeza commented
/ocabot merge nobump

2023-10-10 22:42 UTC, merged